schema_version = "1.0.0"

maintainer = "Daniel Boxer <dani3lb0x3r@gmail.com>"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]

id = "blendir"
name = "BlenDir"
version = "0.20.1"
blender_version_min = "4.2.0"
tagline = "One click custom project folder structure"
website = "https://github.com/DanielBoxer/BlenDir"

# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["System"]

[permissions]
files = "Create folders and save folder structure files"
