name: Package

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      OUTPUT_NAME: "BlenDir"
      INCLUDED_FILES: "src structures LICENSE __init__.py"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move to nested folder
        run: |
          mkdir $OUTPUT_NAME
          mv $INCLUDED_FILES $OUTPUT_NAME

      - name: Zip folder
        run: zip -r ${OUTPUT_NAME}.zip $OUTPUT_NAME

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.OUTPUT_NAME }}.zip
