name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Which part of the version to increment"
        type: choice
        options:
          - major
          - minor
          - patch
        default: "patch"
        required: true

      version:
        description: "Override version increment"
        required: false

env:
  PACKAGE_NAME: "BlenDir"
  INCLUDED_FILES: "src structures LICENSE __init__.py blender_manifest.toml"

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get Next Version
        id: get_version
        uses: danielboxer/next-version-action@v1
        with:
          increment: ${{ github.event.inputs.increment }}
          version: ${{ github.event.inputs.version }}
          use_v_prefix: true

      - name: Move to nested folder
        run: |
          mkdir $PACKAGE_NAME
          mv $INCLUDED_FILES $PACKAGE_NAME

      - name: Zip folder
        run: zip -r ${{ env.PACKAGE_NAME }}.zip ${{ env.PACKAGE_NAME }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          files: ${{ env.PACKAGE_NAME }}.zip
